In [1]:
import sys
sys.version

'3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]'

In [2]:
import numpy as np
np.__version__

'2.3.1'

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [6]:
m = np.array(my_list)
m

array([1, 2, 3, 4, 5])

In [7]:
print(type(m))

<class 'numpy.ndarray'>


In [9]:
print(type(m))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [13]:
np.arange(10,50,5,2)

TypeError: Cannot interpret '2' as a data type

In [14]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [ ]:
np.arange(10,2) # This will not work as the start is greater than the stop

array([], dtype=int64)

In [18]:
n = np.arange(10,30)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [ ]:
np.zeros(10)                # This creates an array of 10 zeros with float data type by default

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.zeros(10, dtype=int)
z                               # Specifying the data type as integer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros((1,2),dtype=int)  # Creates a 2D array with shape (1,2) filled with zeros

array([[0, 0]])

In [ ]:
np.zeros((2,3))  # Creates a 2D array with shape (2,3) filled with zeros with float vlaues

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
z1 = np.zeros((2,4), dtype=int)  # Creates a 2D array with shape (2,4) filled with zeros with integer values

z1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
z2 = np.zeros((5,6), dtype=int)  # Creates a 2D array with shape (2,4) filled with zeros with float values
z2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(20) # Creates an array of 20 ones with float data type by default

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [38]:
o1 = np.ones((2,4), dtype= int)  # Creates a 2D array with shape (2,3) filled with ones with integer values
o1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
o2 = np.ones((20,10), dtype= int)  # Creates a 2D array with shape (2,3) filled with ones with integer values

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [42]:
zero = np.zeros([2,2], dtype=int)  # Creates a 2D array with shape (2,2) filled with zeros with integer values
print(zero)
print(type(zero))

[[0 0]
 [0 0]]
<class 'numpy.ndarray'>


In [ ]:
n = (4,6)
o3 = np.ones(n)  # parameter tuning
o3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
o3 = np.ones(n, dtype=int)  # parameter tuning with integer data type is called hyper parameter tuning
print(o3)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
np.twos(10) # This will not work as there is no function called twos in numpy, it should be np.ones or np.zeros

AttributeError: module 'numpy' has no attribute 'twos'

In [52]:
z2.shape  # Returns the shape of the array

(5, 6)

In [53]:
z2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [54]:
rand(10)

NameError: name 'rand' is not defined

In [55]:
random.rand(10)

NameError: name 'random' is not defined

In [57]:
np.random.rand(10) # Generates an array of 10 random numbers from a uniform distribution over [0.0, 1.0)

array([0.03627611, 0.68917876, 0.23388997, 0.9650721 , 0.19676718,
       0.17341488, 0.71177761, 0.42319314, 0.09584474, 0.36999215])

In [63]:
np.random.randint(10)  # Generates a random integer from 0 to 10 (exclusive)

3

In [ ]:
np.random.rand(10)  # generates an array of 10 random numbers from a uniform distribution over [0.0, 1.0)

array([0.48595551, 0.84979182, 0.50849702, 0.78877295, 0.78211761,
       0.9668089 , 0.24662379, 0.85721284, 0.44391238, 0.73471718])

In [ ]:
np.random.randint(2,4)  # Generates a random integer from 2 to 4 (4 is exclusive)

3

In [77]:
np.random.rand(2,4)  # Generates a 2D array of random numbers with shape (10,20) from a uniform distribution over [0.0, 1.0)

array([[0.44466911, 0.0837688 , 0.26156551, 0.45241484],
       [0.25706323, 0.84540154, 0.58715393, 0.20315048]])

In [ ]:
v = np.random.randint(2,40,2) # Generates a random integer from 2 to 40 (exclusive) count 2
print(v)

[12 28]


In [89]:
print(np.random.randint(2,40,5)) # Generates a random integer from 2 to 40 (exclusive) count 5

[28 11 12 21 29]


In [90]:
print(np.random.randint(2,40,2,5) )

TypeError: Cannot interpret '5' as a data type

In [101]:
print(np.random.randint(2,40,(4,4))) # Generates a 2D array of random integers with shape (2,2) from 2 to 40 (exclusive)

[[29  3 31  8]
 [15  5 35 17]
 [ 4 35 35 15]
 [12 17 32  6]]


In [ ]:
print(np.random.randint(20,4,2) ) # This will not work as the start is greater than the stop, it should be np.random.randint(2,20,2)

ValueError: low >= high

In [ ]:
print(np.random.randint(20,21,2)) # Generates a random integer from 20 to 21 (exclusive) count 2

[20 20]


In [ ]:
print(np.random.randint(-20,8,6)) # Generates a random integer from -20 to 8 (exclusive) count 6

[ -1 -15  -1   2  -2  -7]


In [106]:
bus = np.random.randint(10,20,(4,6))
print(bus)

[[12 17 12 17 18 18]
 [17 13 14 18 12 13]
 [14 15 19 16 10 11]
 [12 16 12 15 10 13]]


In [109]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
np.arange(1,21).reshape(4,5) # Creates a 2D array with shape (4,5) filled with numbers from 1 to 20 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.arange(10,25).reshape(3,5) # Creates a 2D array with shape (3,5) filled with numbers from 10 to 24

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [125]:
print(np.arange(1,13).reshape(12,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [130]:
b = np.random.randint(10,30,(4,6))
print(b)

[[19 20 19 23 29 16]
 [27 15 22 28 12 10]
 [18 21 18 19 29 18]
 [21 16 20 15 29 26]]


In [136]:
print(b[:])

[[19 20 19 23 29 16]
 [27 15 22 28 12 10]
 [18 21 18 19 29 18]
 [21 16 20 15 29 26]]


In [137]:
print(b[::])

[[19 20 19 23 29 16]
 [27 15 22 28 12 10]
 [18 21 18 19 29 18]
 [21 16 20 15 29 26]]


In [134]:
print(b[::-1])

[[21 16 20 15 29 26]
 [18 21 18 19 29 18]
 [27 15 22 28 12 10]
 [19 20 19 23 29 16]]


In [139]:
print(b[::-3])

[[21 16 20 15 29 26]
 [19 20 19 23 29 16]]


In [140]:
b

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10],
       [18, 21, 18, 19, 29, 18],
       [21, 16, 20, 15, 29, 26]], dtype=int32)

In [142]:
print(b[1:4]) # Slicing the array to get rows 1 to 2 (exclusive of 3)

[[27 15 22 28 12 10]
 [18 21 18 19 29 18]
 [21 16 20 15 29 26]]


In [147]:
print(b[0:-2]) # Slicing the array to get rows 0 to 1 (exclusive of 2)

[[19 20 19 23 29 16]
 [27 15 22 28 12 10]]


In [150]:
b[1:5] # Slicing the array to get rows 1 to 4 (exclusive of 5)

array([[27, 15, 22, 28, 12, 10],
       [18, 21, 18, 19, 29, 18],
       [21, 16, 20, 15, 29, 26]], dtype=int32)

In [ ]:
print(b[-3:-2]) # slicing the array to get rows -3 to -2 (exclusive of -1)

[[27 15 22 28 12 10]]


In [157]:
print(b[1:2])

[[27 15 22 28 12 10]]


In [ ]:
print(b[1,2]) # Accessing the element at row 1, column 2

22


In [160]:
b

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10],
       [18, 21, 18, 19, 29, 18],
       [21, 16, 20, 15, 29, 26]], dtype=int32)

In [ ]:
print(b[2,4]) # Accessing the element at row 2, column 4

29


In [163]:
b

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10],
       [18, 21, 18, 19, 29, 18],
       [21, 16, 20, 15, 29, 26]], dtype=int32)

In [ ]:
print(b[1:3]) # slicing the array to get rows 1 to 2 (exclusive of 3)

[[27 15 22 28 12 10]
 [18 21 18 19 29 18]]


In [166]:
print(b[3,-2])

29


In [165]:
print(b[1,-1])

10


In [177]:
b

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10],
       [18, 21, 18, 19, 29, 18],
       [21, 16, 20, 15, 29, 26]], dtype=int32)

In [176]:
b[0:-2]

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10]], dtype=int32)

In [178]:
b[-4:2] 

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10]], dtype=int32)

In [180]:
b1 = np.random.randint(10,30,(5,4))
b1

array([[12, 20, 15, 26],
       [26, 19, 15, 26],
       [12, 19, 23, 14],
       [18, 29, 14, 20],
       [23, 10, 14, 20]], dtype=int32)

In [183]:
b

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10],
       [18, 21, 18, 19, 29, 18],
       [21, 16, 20, 15, 29, 26]], dtype=int32)

In [ ]:
b[-4:2] # Slicing the array to get rows -4 to 1 (exclusive of 2)

array([[19, 20, 19, 23, 29, 16],
       [27, 15, 22, 28, 12, 10]], dtype=int32)

In [ ]:
b1[-4:2] # Slicing the array to get rows -4 to 1 (exclusive of 2)

array([[26, 19, 15, 26]], dtype=int32)

In [208]:
b2 = np.random.randint(10,30,(6,5))
b2

array([[16, 13, 17, 15, 19],
       [19, 25, 28, 11, 20],
       [25, 11, 21, 14, 16],
       [11, 13, 15, 25, 14],
       [13, 11, 15, 19, 26],
       [25, 24, 20, 19, 12]], dtype=int32)

In [212]:
print(b2[1:3])  # Slicing the array to get rows -4 to 1 (exclusive of 2)

[[19 25 28 11 20]
 [25 11 21 14 16]]


In [214]:
print(b2[-5:-3])  # Slicing the array to get rows -4 to 1 (exclusive of 2)

[[19 25 28 11 20]
 [25 11 21 14 16]]


In [225]:
print(b2[-4:-1])  # Slicing the array to get rows -4 to 1 (exclusive of 2)

[[25 11 21 14 16]
 [11 13 15 25 14]
 [13 11 15 19 26]]


In [222]:
print(b2[-6 : -3])   # slicing  = start : end

[[16 13 17 15 19]
 [19 25 28 11 20]
 [25 11 21 14 16]]


In [229]:
a = np.random.randint(10,20,15)
a


array([12, 12, 15, 13, 19, 11, 12, 12, 18, 13, 17, 12, 16, 15, 18],
      dtype=int32)

In [240]:
np.random.randint(2 , 4 , 6)

array([2, 3, 2, 3, 3, 3], dtype=int32)

In [241]:
np.random.randint(5,7,20)  # Generates a random integer from 10 to 20 (exclusive) count 15

array([6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 5],
      dtype=int32)

In [256]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[36, 77, 44, 12, 12,  1,  9, 15, 75,  4],
       [79, 79, 70, 13,  8, 75, 81, 53, 23, 79],
       [52, 67, 45, 23, 28, 11, 38, 40,  6, 90],
       [60, 52, 33,  1, 52, 96, 12, 98, 62, 36],
       [11, 16, 11, 87, 88, 65, 68, 69, 57, 86],
       [39, 26, 39, 82, 63, 62, 45, 34, 98, 94],
       [97, 63, 12, 99,  3, 90, 45, 13, 60, 68],
       [60, 89, 26, 73, 33, 28, 58, 56, 20, 61],
       [60, 95, 86,  3,  2, 63, 79, 65,  5, 83],
       [11, 45, 16, 64, 73,  7, 58, 21, 59, 46]], dtype=int32)

In [261]:
arr2[:]

array([[36, 77, 44, 12, 12,  1,  9, 15, 75,  4],
       [79, 79, 70, 13,  8, 75, 81, 53, 23, 79],
       [52, 67, 45, 23, 28, 11, 38, 40,  6, 90],
       [60, 52, 33,  1, 52, 96, 12, 98, 62, 36],
       [11, 16, 11, 87, 88, 65, 68, 69, 57, 86],
       [39, 26, 39, 82, 63, 62, 45, 34, 98, 94],
       [97, 63, 12, 99,  3, 90, 45, 13, 60, 68],
       [60, 89, 26, 73, 33, 28, 58, 56, 20, 61],
       [60, 95, 86,  3,  2, 63, 79, 65,  5, 83],
       [11, 45, 16, 64, 73,  7, 58, 21, 59, 46]], dtype=int32)

In [263]:
arr2[::4]

array([[36, 77, 44, 12, 12,  1,  9, 15, 75,  4],
       [11, 16, 11, 87, 88, 65, 68, 69, 57, 86],
       [60, 95, 86,  3,  2, 63, 79, 65,  5, 83]], dtype=int32)

In [266]:
arr2[::-1]

array([[11, 45, 16, 64, 73,  7, 58, 21, 59, 46],
       [60, 95, 86,  3,  2, 63, 79, 65,  5, 83],
       [60, 89, 26, 73, 33, 28, 58, 56, 20, 61],
       [97, 63, 12, 99,  3, 90, 45, 13, 60, 68],
       [39, 26, 39, 82, 63, 62, 45, 34, 98, 94],
       [11, 16, 11, 87, 88, 65, 68, 69, 57, 86],
       [60, 52, 33,  1, 52, 96, 12, 98, 62, 36],
       [52, 67, 45, 23, 28, 11, 38, 40,  6, 90],
       [79, 79, 70, 13,  8, 75, 81, 53, 23, 79],
       [36, 77, 44, 12, 12,  1,  9, 15, 75,  4]], dtype=int32)

In [264]:
arr2[::-2] 

array([[11, 45, 16, 64, 73,  7, 58, 21, 59, 46],
       [60, 89, 26, 73, 33, 28, 58, 56, 20, 61],
       [39, 26, 39, 82, 63, 62, 45, 34, 98, 94],
       [60, 52, 33,  1, 52, 96, 12, 98, 62, 36],
       [79, 79, 70, 13,  8, 75, 81, 53, 23, 79]], dtype=int32)

In [267]:
arr2

array([[36, 77, 44, 12, 12,  1,  9, 15, 75,  4],
       [79, 79, 70, 13,  8, 75, 81, 53, 23, 79],
       [52, 67, 45, 23, 28, 11, 38, 40,  6, 90],
       [60, 52, 33,  1, 52, 96, 12, 98, 62, 36],
       [11, 16, 11, 87, 88, 65, 68, 69, 57, 86],
       [39, 26, 39, 82, 63, 62, 45, 34, 98, 94],
       [97, 63, 12, 99,  3, 90, 45, 13, 60, 68],
       [60, 89, 26, 73, 33, 28, 58, 56, 20, 61],
       [60, 95, 86,  3,  2, 63, 79, 65,  5, 83],
       [11, 45, 16, 64, 73,  7, 58, 21, 59, 46]], dtype=int32)

In [ ]:
arr2[1:3,3:5] # Accessing a subarray from row 1 to 2 (exclusive of 3) and column 3 to 4 (exclusive of 5)

array([[13,  8],
       [23, 28]], dtype=int32)

In [270]:
arr2[2:4, 1:6]

array([[67, 45, 23, 28, 11],
       [52, 33,  1, 52, 96]], dtype=int32)

In [274]:
arr2.max()

np.int32(99)

In [275]:
arr2.min()

np.int32(1)

In [276]:
arr2.mean()

np.float64(48.82)

In [287]:
from numpy import *
a = array([1,2,3,4,5,6,7,8])
median(a)

np.float64(4.5)

In [288]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [291]:
a.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [289]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a.reshape(8,1) # vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [295]:
a.reshape((2,4), order='C')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [305]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [306]:
row = 5
col = 4
print(mat[row,col])

54


In [ ]:
mat[6] #to access the 6th row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat[:,col] # To access all rows of column 4

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [309]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [310]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [311]:
mat[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [312]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [313]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [314]:
mat[:8]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [316]:
mat[:,-2]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [317]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [325]:
mat[::3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [323]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [328]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[2:5,6:8] ## 2:5 --> only row part /// 6:8 -- it indicates only column parts

array([[26, 27],
       [36, 37],
       [46, 47]])

In [335]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [336]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [337]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [338]:
mat[mat==50]

array([50])