# numpy basics

In [2]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [3]:
import numpy as np
np.__version__

'1.26.4'

In [5]:
my_list = [0,1,2,3,4,5]
print(my_list)
type(my_list)

[0, 1, 2, 3, 4, 5]


list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
print(type(arr)) # nd array means n dimentional array

<class 'numpy.ndarray'>


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [16]:
np.arange(10,20,3,5)

TypeError: Cannot interpret '5' as a data type

In [20]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [21]:
n = np.arange(8,20)
n

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros(3,dtype = int)

array([0, 0, 0])

In [25]:
np.zeros(4,dtype = float)

array([0., 0., 0., 0.])

In [27]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.zeros((3,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
n = np.zeros((5,9),dtype = int)
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
len(n)

5

In [39]:
np.ones(3, dtype= int)

array([1, 1, 1])

In [42]:
nd1 = np.ones((10,10),dtype= int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [43]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])